### ISSUE TITLE
Make nice picture of real-life CNDY usage in the ioki office

### ISSUE THREAD

**Issue by fabrik42** [fabrik42/cndy-internal#3]
Maybe Stefan helps :)

**Comment by chr4** [comment]
Stefan hat zugesagt, leider hat sich nur einer freiwillig gemeldet bis jetzt.

**Comment by fabrik42** [comment]
Dann musst du wohl mit guten Beispiel voran gehen 😬

Aber Stillleben von den QR codes wär imho auch schon cool. Hauptsache man erkennt es ist RL und es sieht cool aus ;)

**Comment by fabrik42** [comment]
Done!
